sdk: "accelerator-sdk.yaml"
host: "0.0.0.0"
port: 8090
userName: "Admin"
organization: "org1.example.com"
batch:
  ##### Simple #####
  - type: "execute"
    channelId: "mychannel"
    chaincodeName: "simple"
    fcn: "open"
    queueSize: 1000
    maxWaitTimeSeconds: 1
    maxBatchItems: 10
  - type: "execute"
    channelId: "mychannel"
    chaincodeName: "simple"
    fcn: "delete"
    queueSize: 1000
    maxWaitTimeSeconds: 1
    maxBatchItems: 10
  - type: "query"
    channelId: "mychannel"
    chaincodeName: "simple"
    fcn: "query"
    queueSize: 1000
    maxWaitTimeSeconds: 1
    maxBatchItems: 10
  - type: "execute"
    channelId: "mychannel"
    chaincodeName: "simple"
    fcn: "transfer"
    queueSize: 1000
    maxWaitTimeSeconds: 1
    maxBatchItems: 10

  ##### Smallbank #####
  - type: "execute"
    channelId: "mychannel"
    chaincodeName: "smallbank"
    fcn: "create_account"
    queueSize: 1000
    maxWaitTimeSeconds: 1
    maxBatchItems: 10
    readKeyIndices:
      - 0
    writeKeyIndices:
      - 0
  - type: "execute"
    channelId: "mychannel"
    chaincodeName: "smallbank"
    fcn: "deposit_checking"
    queueSize: 1000
    maxWaitTimeSeconds: 1
    maxBatchItems: 10
    readKeyIndices:
      - 1
    writeKeyIndices:
      - 1
  - type: "execute"
    channelId: "mychannel"
    chaincodeName: "smallbank"
    fcn: "write_check"
    queueSize: 1000
    maxWaitTimeSeconds: 1
    maxBatchItems: 10
    readKeyIndices:
      - 1
    writeKeyIndices:
      - 1
  - type: "execute"
    channelId: "mychannel"
    chaincodeName: "smallbank"
    fcn: "transact_savings"
    queueSize: 1000
    maxWaitTimeSeconds: 1
    maxBatchItems: 10
    readKeyIndices:
      - 1
    writeKeyIndices:
      - 1
  - type: "execute"
    channelId: "mychannel"
    chaincodeName: "smallbank"
    fcn: "send_payment"
    queueSize: 1000
    maxWaitTimeSeconds: 1
    maxBatchItems: 10
    readKeyIndices:
      - 1
      - 2
    writeKeyIndices:
      - 1
      - 2
  - type: "execute"
    channelId: "mychannel"
    chaincodeName: "smallbank"
    fcn: "amalgamate"
    queueSize: 1000
    maxWaitTimeSeconds: 1
    maxBatchItems: 10
    readKeyIndices:
      - 0
      - 1
    writeKeyIndices:
      - 0
      - 1
  - type: "query"
    channelId: "mychannel"
    chaincodeName: "smallbank"
    fcn: "query"
    queueSize: 1000
    maxWaitTimeSeconds: 1
    maxBatchItems: 10
    readKeyIndices:
      - 0