---
test:
  name: simple
  description: This is an example benchmark for caliper, to test the backend DLT's
    performance with simple account opening & querying transactions
  clients:
    type: local
    number: 5
  rounds:
  - label: open
    txNumber:
    - 1000
    - 1000
    - 1000
    - 1000
    - 1000
    rateControl:
    - type: fixed-rate
      opts:
        tps: 100
    - type: fixed-rate
      opts:
        tps: 200
    - type: fixed-rate
      opts:
        tps: 300
    - type: fixed-rate
      opts:
        tps: 400
    - type: fixed-rate
      opts:
        tps: 500
    arguments:
      money: 10000
    callback: benchmark/simple/open.js
  - label: query
    txNumber:
    - 1000
    - 1000
    - 1000
    - 1000
    - 1000
    rateControl:
    - type: fixed-rate
      opts:
        tps: 200
    - type: fixed-rate
      opts:
        tps: 400
    - type: fixed-rate
      opts:
        tps: 600
    - type: fixed-rate
      opts:
        tps: 800
    - type: fixed-rate
      opts:
        tps: 1000
    callback: benchmark/simple/query.js
monitor:
  type:
  - docker
  - process
  docker:
    name:
    - all
  process:
  - command: node
    arguments: local-client.js
    multiOutput: avg
  interval: 1
